### ISSUE TITLE
Get all of the badges

### ISSUE THREAD

**Issue by codymikol** [codymikol/game-kiln#55]
We should add badges to the page so it looks real good and stuff.

@berslucas what was that site to add badges to your repo?

Like this

![image](https://user-images.githubusercontent.com/13606342/54470303-e892e000-477b-11e9-9103-7c06a6ccb512.png)

**Comment by bersLucas** [comment]
website is https://shields.io/

**Comment by codymikol** [comment]
Thanks m8!

**Comment by codymikol** [comment]
@bersLucas this site is cool too https://badgen.net/
